### 1. Register a NEW user (with scrambled password)
POST http://localhost:8081/api/users/register
Content-Type: application/json

{
  "username": "chamrong_dev",
  "password": "mysecurepassword123",
  "email": "chamrong@school.com",
  "role": "ADMIN"
}

### 2. Login to get the JWT Token
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "chamrong@school.com",
  "password": "mysecurepassword123"
}